### ISSUE TITLE
Getting the error message "Killedlding for..." while running step 0 (bootstrapping).

### ISSUE THREAD

**Issue by mustafa-yilmaz-zz** [Urigo/meteor-angular2.0-socially#91] opened 2016-05-19 07:45 UTC
I share my screenshot taken from "codeanywhere" web IDE.

I did not try to execute the instructions in any other environment, so I do not know if there is something specific to "codeanywhere" (as, I guess, there was once something for "nitrous.io" in the past as it is written [here](http://quabr.com/29448886/discover-meteor-mongo-nitrous-issue) ) but I can provide a connection to the project if needed and/or requested.

Thanks very much in advance for any help.

Regards,

Mustafa

![killedlding](https://cloud.githubusercontent.com/assets/878471/15416483/9c3f1ece-1e54-11e6-90bd-cfdcab76690d.png)

**Comment by serkandurusoy** [comment] 2016-05-20 06:31
Some web ide's have been reported to do that but frankly I never took much interest in those so I don't know what the root cause may be. If you are able to run the app locally, you will have (partially) verified that.

It looks like codeanywhere is not letting the app instance start its own mongodb instance. Ask codeanywhere support how you can start a mongodb instance in your environment and if it is not possible, try using an external db from mlab or compose.

**Comment by kamilkisiela** [comment] 2016-06-02 13:18
It looks like it's not related to `meteor-angular2.0-socially`. Could you try to run an app that is totally independent of `angular2-meteor`?

Right now, I'm closing this issue but feel free to reopen it! :)

**Closed as completed by kamilkisiela** 2016-06-02 13:18 UTC
