### ISSUE TITLE
step 3.3

### ISSUE THREAD

**Issue by shotleybuilder** [Urigo/meteor-angular2.0-socially#14] opened 2015-12-06 17:26 UTC
I could only get this to work as:

```
import {Parties} from '../collections/parties';
```

**Comment by shotleybuilder** [comment] 2015-12-06 17:42
Think I went off a bit early.
However, I'm using the https://atom.io/packages/atom-typescript add-in and this flags this up as a 'Cannot find module' error.
Bit disconcerting for a newbie to Angular2.  Having gotten my head around using angular-meteor this is a whole lot more ... learning :-)

**Comment by barbatus** [comment] 2015-12-08 10:56
Ok, if the issue is in the atom, then I am going to close it.

**Comment by ShMcK** [comment] 2015-12-08 11:16
In Atom, try creating a `tsconfig.json` file that will let atom-typescript know what files you are using. Here's the quick and easy way.
1. `cmd + shift + p` to bring up the search bar 
2. autocomplete to find "Typescript: create Tsconfig.json project file", press enter
3. change the `tsconfig.json` settings so that it won't compile or build, leave that to Meteor

```
    "compileOnSave": false,
    "buildOnSave": false
```

Atom-Typescript should now be aware of your files (see `filesGlob`), and you won't even need to use `/// <reference path...` anymore. For more info on tsconfig in atom-typescript look [here](https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md).

**Comment by barbatus** [comment] 2015-12-08 11:45
@ShMcK thanks for the comment. I feel like it has sense to update the tutorial's TypeScript step with this kind of information.

**Comment by ShMcK** [comment] 2015-12-08 11:49
@barbatus, maybe we should just make sure it fixes the issue first. If so, I could add an edit to the tutorial for those using Atom.

However, using a `tsconfig.json` file altogether would eliminate the need for `/// <reference path>`'s. It could be automated by the typescript compiler module.

**Comment by barbatus** [comment] 2015-12-08 11:54
@ShMcK Yes, you are right. A couple of people had similar complains (like [here](https://github.com/Urigo/Meteor-Angular2/issues/25)), ultimately related, I guess, to the `compileOnSave` and `buildOnSave` options.

**Comment by Urigo** [comment] 2016-01-07 15:14
Deployed, please check if it fixes the problem

**Closed as completed by Urigo** 2016-01-07 15:14 UTC

**Comment by pagas** [comment] 2016-06-14 21:29
Hi everyone, 
I have similar issue. Trying to compile socially project and getting this error: 
Error: A method named '/parties/insert' is already defined 

So, I've understood that there is a duplicate typescript compilation, by Atom which I am using and Meteor. Ok, So I am trying to disable it by adding there rules to tsconfig.json file: 
    "compileOnSave": false,
    "buildOnSave": false,
and then I am compiling meteor it spits out another error: 
barbatus_typescript-compiler\node_modules\meteor-typescript\options.js:76:11:
   Unknown compiler option 'compileOnSave'. 

How to make barbatus typescript compiler understand 'compilerOnSave' rule??
Cause if I delete parties.js and parties.js.map files manually meteor compiles everything fine.

I need to disable atom's default typescript compilation, but I cant.. So, I need to delete those files manually? is there any solution to this issue??
Thank you for you time.
