### ISSUE TITLE
angular-cli in angular2-meteor project

### ISSUE THREAD

**Issue by neeraj1928** [Urigo/meteor-angular2.0-socially#161] opened 2016-10-04 05:26 UTC
Angular2 cli makes development process really fast. They help in fast generation of components, services etc. and automatically write high level repetitive codes. But in project developed using angular2-meteor, its not working.

**Comment by hongbo-miao** [comment] 2016-10-14 18:20
Hi @neeraj1928 please track this https://github.com/Urigo/angular2-meteor/issues/280

**Comment by dotansimha** [comment] 2016-10-18 11:14
@neeraj1928 , I am closing this issue since it's not related directly to the Angular2-Meteor Socially tutorial, please track it in https://github.com/Urigo/angular2-meteor/issues/280.

Thanks.

**Closed as completed by dotansimha** 2016-10-18 11:14 UTC

**Comment by neeraj1928** [comment] 2016-10-18 11:23
OK. But I raised it here to make a point that some integration should be there.

**Comment by Urigo** [comment] 2016-10-18 15:28
@neeraj1928 the question is, what integration do you want?
or more importantly, what's missing?
The problem is, the angular-cli is changing so much these days, I don't think it's a solid thing.
